version: "3.3"
services:
  redis:
    image: redis:latest
    container_name: composed-redis
    volumes:
      - type: volume
        source: mydata
        target: /data
    ports:
    - 6379:6379

  grafana:
    image: grafana/grafana
    container_name: composed-grafana
    ports:
    - 3000:3000

volumes:
  mydata: