braze:
  api:
    key:
  host:
    name: https://rest.iad-03.braze.com
  endpoint:
    user:
      track: /users/track
      delete: /users/delete

thai:
  currency:
    thai-baht: ฿

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, metrics, prometheus